#!/bin/env sh

# Prepare some stuff.
packages_arg="++"
cd "$(dirname "$0")"
mkdir -p "$HOME/.local/share/fonts/"

# -- Fonts
cp -f $PWD/assets/fonts/* "$HOME/.local/share/fonts/"
# -- Bash
ln -sf "$PWD/bash/.bashrc" "$HOME/.bashrc"
# -- Kitty
ln -sf "$PWD/kitty/kitty.conf" "$HOME/.config/kitty/kitty.conf"
# -- Nano
ln -sf "$PWD/nano/.nanorc" "$HOME/.nanorc"
ln -sf "$PWD/nano/.nanotc" "$HOME/.nanotc"
# No idea why I get a link inside there.
rm -f "$PWD/nano/.nanotc/.nanotc"

for arg in "$@"; do
    if [ "$arg" = "$packages_arg" ]; then
        sudo add-apt-repository ppa:zhangsongcui3371/fastfetch
        sudo apt update
        sudo apt install \
            build-essential \
            git \
            subversion \
            valgrind \
            entr \
            fastfetch \
            dmd \
            ldc \
            kitty \
            pluma \
            wine \
            gimp \
            inkscape \
            ascii \
            cloc \
            dos2unix
        continue
    fi
    echo "What do you mean by \"$arg\"? This is not funny."
    break
done

echo "Done!"
