#!/bin/env sh

# This script just works. It will delete old files, so keep that in mind.

# Some words:
# * rc: Run commands
# * tc: Theme commands

hello_arg="hello" # This will say hello.
packages_arg="++" # This will download some packages.

cd "$(dirname "$0")"
ln -sf "$PWD/bash/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/nano/.nanorc" "$HOME/.nanorc"
ln -sf "$PWD/nano/.nanotc" "$HOME/.nanotc"
rm -f "$PWD/nano/.nanotc/.nanotc" # No idea why I get a link inside there.

for arg in "$@"; do
    if [ "$arg" = "$hello_arg" ]; then
        echo "Hello. How are you?"
        echo -n "> "
        read input
        echo "Great!"
        continue
    fi
    if [ "$arg" = "$packages_arg" ]; then
        echo "Installing packages."
        sudo apt install \
            build-essential git \
            entr \
            dmd ldc \
            wine gimp inkscape
        continue
    fi
    echo "What do you mean by \"$arg\"? This is not funny."
    break
done

echo "Done!"
