#!/bin/env sh

## A script that automatically runs DUB projects when a file changes.

name="dubwatch"

if [ -d "$1" ]; then
    cd "$1"
    echo "Watching!"
    find -name '*.d' | entr -p dub run -- "$2" "$3" "$4" "$5" "$6" "$7"
else
    echo "Usage: $name <project> [args]"
fi
