#!/bin/env sh

## A script that creates a builder for Parin games.

dir="$(dirname "$0")"
if [ "$1" = "." ]; then
    cp "$dir/../d/buildparin.d" "."
else
    dmd -ofbuild "$dir/../d/buildparin.d"
    rm -f build.o
fi
